version: 2

sphinx:
    builder: html
    configuration: seisflows/docs/conf.py

python:
    version: 3.7
    install:
        - requirements: seisflows/docs/requirements.txt
        - requirements: requirements.txt
        - method: setuptools
          path: .

conda:
    environment: seisflows/docs/environment.yml
