# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#                 Seisflows YAML Parameter File and Path Input
#
#   variables set to '', or `null`, will be ignored and set to default values 
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#                                    MODULES                                  
#
# These modules correspond to the structure of the source code, determining
# which modules are loaded at runtime. Each of these modules may also 
# correspond to a sub-set of parameters below, which in turn may have custom
# parameters that relate to overwritten/super'd modules
# 
#
# PARAMETERS:
# -----------
# WORKFLOW: The method for running Seisflows
# SOLVER: External solver to use
# SYSTEM: Computer architecture
# OPTIMIZE: Optimization algorithm for the inverse problem
# LINESEARCH: Line-search algorithm to be used in optimization
# PREPROCESS: Preprocessing schema for waveform data
# POSTPROCESS: Postprocessing schema for kernel and gradients
#
# ==============================================================================
WORKFLOW: inversion
SOLVER: specfem3d
SYSTEM: serial
OPTIMIZE: LBFGS 
LINESEARCH: backtrack
PREPROCESS: pyatoa
POSTPROCESS: base
