# //////////////////////////////////////////////////////////////////////////////
#
#                        SeisFlows3 YAML Parameter File
#
# //////////////////////////////////////////////////////////////////////////////
#
# Modules correspond to the structure of the source code, and determine
# SeisFlows3' behavior at runtime. Each module requires its own sub-parameters.
#
# .. rubric::
#   - To determine available options for modules listed below, run:
#       > seisflows print modules
#   - To auto-fill with docstrings and default values (recommended), run:
#       > seisflows configure
#   - To set values as NoneType, use: null
#   - To set values as infinity, use: inf
#
#                                    MODULES
#                                    ///////
# WORKFLOW (str):    The method for running SeisFlows3; equivalent to main()
# SOLVER (str):      External numerical solver to use for waveform simulations
# SYSTEM (str):      Computer architecture of the system being used
# OPTIMIZE (str):    Optimization algorithm for the inverse problem
# PREPROCESS (str):  Preprocessing schema for waveform data
# POSTPROCESS (str): Postprocessing schema for kernels and gradients
# ==============================================================================
WORKFLOW: inversion
SOLVER: specfem2d
SYSTEM: workstation
OPTIMIZE: LBFGS 
PREPROCESS: base
POSTPROCESS: base
